<?php
return array(
    'columns' => array(
        'user_id' => array(
            'type' => 'table:user',
            'in_list' => false,
            'required' => true,
            'default_in_list' => false,
            'label' => app::get('sysuser')->_('会员'),
        ),
        'total' => array(
            'type' => 'string',
            'length' => 20,
            'in_list' => true,
            'default_in_list' => true,
            'default' => 0,
            'comment' => app::get('sysuser')->_('会员总积分,即 信用积分(基础积分+交易积分*(1/10)+评价积分 多个频道积分求和)'),
            'label' => app::get('sysuser')->_('会员总积分(信用积分)'),
        ),
        'base' => array(
            'type' => 'bigint',
            'in_list' => true,
            'default_in_list' => true,
            'default' => 0,
            'comment' => app::get('sysuser')->_('会员基础积分'),
            'label' => app::get('sysuser')->_('会员基础积分'),
        ),
        'seller_ex' => array(
            'type' => 'bigint',
            'in_list' => true,
            'default_in_list' => true,
            'default' => 0,
            'comment' => app::get('sysuser')->_('卖家激励积分'),
            'label' => app::get('sysuser')->_('卖家激励积分'),
        ),
		'seller_trade' => array(
            'type' => 'bigint',
            'in_list' => true,
            'default_in_list' => true,
            'default' => 0,
            'comment' => app::get('sysuser')->_('卖家交易积分'),
            'label' => app::get('sysuser')->_('卖家交易积分'),
        ),
		'seller_rate' => array(
            'type' => 'bigint',
            'in_list' => true,
            'default_in_list' => true,
            'default' => 0,
            'comment' => app::get('sysuser')->_('卖家评价积分'),
            'label' => app::get('sysuser')->_('卖家评价积分'),
        ),
		'temai_ex' => array(
            'type' => 'bigint',
            'in_list' => true,
            'default_in_list' => true,
            'default' => 0,
            'comment' => app::get('sysuser')->_('平台展销激励积分'),
            'label' => app::get('sysuser')->_('卖家激励积分'),
        ),
		'temai_trade' => array(
            'type' => 'bigint',
            'in_list' => true,
            'default_in_list' => true,
            'default' => 0,
            'comment' => app::get('sysuser')->_('平台展销交易积分'),
            'label' => app::get('sysuser')->_('卖家交易积分'),
        ),
		'temai_rate' => array(
            'type' => 'bigint',
            'in_list' => true,
            'default_in_list' => true,
            'default' => 0,
            'comment' => app::get('sysuser')->_('平台展销评价积分'),
            'label' => app::get('sysuser')->_('卖家评价积分'),
        ),
		'proofing_ex' => array(
            'type' => 'bigint',
            'in_list' => true,
            'default_in_list' => true,
            'default' => 0,
            'comment' => app::get('sysuser')->_('服务撮合激励积分'),
            'label' => app::get('sysuser')->_('服务撮合激励积分'),
        ),
		'proofing_trade' => array(
            'type' => 'bigint',
            'in_list' => true,
            'default_in_list' => true,
            'default' => 0,
            'comment' => app::get('sysuser')->_('服务撮合交易积分'),
            'label' => app::get('sysuser')->_('服务撮合交易积分'),
        ),
		'proofing_rate' => array(
            'type' => 'bigint',
            'in_list' => true,
            'default_in_list' => true,
            'default' => 0,
            'comment' => app::get('sysuser')->_('服务撮合评价积分'),
            'label' => app::get('sysuser')->_('卖家评价积分'),
        ),
    ),
    'primary' => 'user_id',
    'index' => array(
    ),
    'comment' => app::get('sysuser')->_('会员信用积分表'),
);
