<?php
return  array(
    'columns'=> array(
        'temai_id' => array(
            'type' => 'number',
            //'pkey' => true,
            'autoincrement' => true,
            'required' => true,
            'comment' => app::get('systemai')->_('temai_id'),
        ),
        'user_id' => array(
            'type' => 'table:user@sysuser',
            'required' => true,
            'label' => app::get('systemai')->_('所属平台展销会员'),
            'comment' => app::get('systemai')->_('会员id'),
            'in_list' => true,
            'default_in_list' => false,
            'order' => 11,
        ),
        'item_id' => array(
            'type' => 'table:item@sysitem',
            'required' => true,
            'label' => app::get('systemai')->_('商品id'),
            'comment' => app::get('systemai')->_('商品id'),
            'finder_filter_name'=>'item_id',
            'in_list' => false,
            'default_in_list' => false,
            'filtertype' => 'yes',
            'filterdefault' => true,
            'order' => 13,
        ),
        'title' => array(
            'type' => 'string',
            'length' => 90,
            'required' => true,
            'default' => '',
            'label' => app::get('systemai')->_('商品平台展销标题'),
            'comment' => app::get('systemai')->_('商品平台展销标题'),
            'in_list' => true,
            'default_in_list' => false,
            'is_title' => false,
            'searchtype' => 'has',
            'filtertype' => 'custom',
            'filterdefault' => true,
            'order' => 12,
        ),
        'sub_title' => array(
            'type' => 'string',
            'length' => 200,
            'label' => app::get('systemai')->_('商品平台展销子标题'),
            'comment' => app::get('systemai')->_('商品平台展销子标题'),
            'filtertype' => 'normal',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'price' => array(
            'type' => 'money',
            'required' => true,
			'default'	=> 0,
            'label' => app::get('systemai')->_('平台商品定价'),
            'comment' => app::get('systemai')->_('平台商品定价'),
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 15,
        ),
        'temai_price' => array(
            'type' => 'money',
			'default'	=> 0,
            'label' => app::get('systemai')->_('卖家商品价'),
            'comment' => app::get('systemai')->_('卖家商品价'),
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 16,
        ),
        'mkt_price' => array(
            'type' => 'money',
            'required' => true,
			'default'	=> 0,
            'label' => app::get('systemai')->_('商品原价'),
            'comment' => app::get('systemai')->_('商品原价'),
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 16,
        ),
		'store' => array(
			'type' => 'number',
			'default' => 0,
			'in_list' => true,
			'default_in_list' => true,
			'comment' => app::get('systemai')->_('平台库存'),
			'label' => app::get('systemai')->_('平台库存'),
			'order' => 17,
		),
		'store_total' => array(
			'type' => 'number',
			'default' => 0,
			'in_list' => true,
			'default_in_list' => true,
			'comment' => app::get('systemai')->_('商家总库存'),
			'label' => app::get('systemai')->_('商家总库存'),
			'order' => 18,
		),
		'cat' => array(
            'type' => 'number',
			'default' => 0,
            'in_list' => true,
            'default_in_list' => true,
            'comment' => app::get('systemai')->_('所属类型'),
            'label' => app::get('systemai')->_('所属类型'),
			'order' => 17,
        ),
		'sale_num' => array(
            'type' => 'number',
			'default' => 0,
            'in_list' => false,
            'default_in_list' => false,
            'comment' => app::get('systemai')->_('销量'),
            'label' => app::get('systemai')->_('销量'),
			'order' => 17,
        ),
		'click_num' => array(
            'type' => 'number',
			'default' => 0,
            'in_list' => false,
            'default_in_list' => false,
            'comment' => app::get('systemai')->_('点击量'),
            'label' => app::get('systemai')->_('点击量'),
			'order' => 17,
        ),
		'starttime' => array(
            'type' => 'time',
			'default' => 0,
            'in_list' => true,
            'default_in_list' => true,
            'comment' => app::get('systemai')->_('平台展销申请开始时间'),
            'label' => app::get('systemai')->_('平台展销申请开始时间'),
			'order' => 18,
        ),
		'endtime' => array(
            'type' => 'time',
            'default' => 0,
            'in_list' => true,
            'default_in_list' => true,
            'comment' => app::get('systemai')->_('平台展销申请结束时间'),
            'label' => app::get('systemai')->_('平台展销申请结束时间'),
			'order' => 19,
        ),
		'tm_starttime' => array(
			'type' => 'time',
			'default' => 0,
			'in_list' => true,
			'default_in_list' => false,
			'comment' => app::get('systemai')->_('平台设定本次开始时间'),
			'label' => app::get('systemai')->_('平台设定本次开始时间'),
			'order' => 18,
		),
		'tm_endtime' => array(
			'type' => 'time',
			'default' => 0,
			'in_list' => true,
			'default_in_list' => false,
			'comment' => app::get('systemai')->_('平台设定本次结束时间'),
			'label' => app::get('systemai')->_('平台设定本次结束时间'),
			'order' => 19,
		),
		'state' => array(
            'type' => [
				0 => '待上架(待审核)',
				1 => '已上架',
				2 => '已下架',
				3 => '审核不通过',
			],
			'default' => 0,
			'length' => 4,
            'in_list' => true,
            'default_in_list' => false,
            'comment' => app::get('systemai')->_('商品状态 0待上架(待审核),1已上架,2已下架,3审核不通过'),
            'label' => app::get('systemai')->_('商品状态'),
        ),
        'batch' => array(
            'type' => 'string',
            'length' => 50,
            'in_list' => true,
            'default_in_list' => false,
            'comment' => app::get('systemai')->_('批次'),
            'label' => app::get('systemai')->_('批次'),
            'order' => 20
        ),
		'reason' => array(
            'type' => 'string',
            'in_list' => true,
            'default_in_list' => false,
            'comment' => app::get('systemai')->_('审核不通过原因'),
            'label' => app::get('systemai')->_('审核不通过原因'),
			'order' => 20
        ),
		'agreement' => array(
			'type' => 'string',
			'in_list' => true,
			'default_in_list' => false,
			'comment' => app::get('systemai')->_('平台展销协议加盖公章附件'),
			'label' => app::get('systemai')->_('平台展销协议加盖公章附件'),
			'order' => 20
		),
		'certificate' => array(
			'type' => 'string',
			'in_list' => true,
			'default_in_list' => false,
			'comment' => app::get('systemai')->_('授权证明文件'),
			'label' => app::get('systemai')->_('授权证明文件'),
			'order' => 20
		),
		'pricecerti' => array(
			'type' => 'string',
			'in_list' => true,
			'default_in_list' => false,
			'comment' => app::get('systemai')->_('销售证明附件'),
			'label' => app::get('systemai')->_('销售证明附件'),
			'order' => 20
		),
		'addtime' => array(
            'type' => 'time',
            'in_list' => true,
            'default_in_list' => false,
            'comment' => app::get('systemai')->_('创建时间'),
            'label' => app::get('systemai')->_('创建时间'),
        ),
        'passtime' => array(
            'type' => 'time',
            'in_list' => true,
            'default_in_list' => false,
            'comment' => app::get('systemai')->_('审核通过'),
            'label' => app::get('systemai')->_('审核通过'),
        ),
        'lasttime' => array(
            'type' => 'last_modify',
            'required' => true,
            'label' => app::get('systemai')->_('更新时间'),
            'comment' => app::get('systemai')->_('最后更新时间'),
            'in_list' => true,
            'default_in_list' => false,
            'order' => 17,
        ),
    ),
    'primary' => 'temai_id',
    'index' => array (
        'ind_title' => ['columns' => ['title']],
        'ind_user_id' => ['columns' => ['user_id']],
        'ind_item_id' => ['columns' => ['item_id']],
		'ind_user_id_item_id' => ['columns' => ['user_id', 'item_id']],
		'ind_state' => ['columns' => ['state']],
        'ind_cat' => ['columns' => ['cat']],
        'ind_sale_num' => ['columns' => ['sale_num']],
        'ind_click_num' => ['columns' => ['click_num']],
    ),
    'comment' => app::get('systemai')->_('平台展销主表'),
);