<?php
return array(
    'columns'=> array(
        'id' => array(
            'type' => 'number',
            'autoincrement' => true,
            'required' => true,
            'comment' => app::get('systemai')->_('id'),
        ),
        'item_id' => array(
            'type' => 'table:item@sysitem',
            'required' => true,
            'label' => app::get('systemai')->_('商品id'),
            'comment' => app::get('systemai')->_('商品id'),
            'finder_filter_name'=>'item_id',
            'in_list' => true,
            'default_in_list' => false,
            'filtertype' => 'yes',
            'filterdefault' => true,
            'order' => 13,
        ),
        'sku_id' => array(
            'type' => 'table:sku@sysitem',
			'default' => 0,
            'finder_filter_name'=>'brand_name',
            'label' => app::get('systemai')->_('商品规格id'),
            'comment' => app::get('systemai')->_('商品规格id'),
            'in_list' => false,
            'default_in_list' => false,
            'filtertype' => 'yes',
            'filterdefault' => false,
            'order' => 14,
        ),
        'price' => array(
            'type' => 'money',
            'required' => true,
			'default'	=> 0,
            'label' => app::get('systemai')->_('平台商品定价'),
            'comment' => app::get('systemai')->_('平台商品定价'),
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 15,
        ),
        'temai_price' => array(
            'type' => 'money',
			'default'	=> 0,
            'label' => app::get('systemai')->_('卖家商品价'),
            'comment' => app::get('systemai')->_('卖家商品价'),
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 16,
        ),
        'mkt_price' => array(
            'type' => 'money',
            'required' => true,
			'default'	=> 0,
            'label' => app::get('systemai')->_('商品原价'),
            'comment' => app::get('systemai')->_('商品原价'),
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 16,
        ),
		'store' => array(
            'type' => 'number',
			'default' => 0,
            'in_list' => true,
            'default_in_list' => true,
            'comment' => app::get('systemai')->_('库存'),
            'label' => app::get('systemai')->_('库存'),
			'order' => 17,
        ),
        'store_total' => array(
            'type' => 'number',
            'default' => 0,
            'in_list' => true,
            'default_in_list' => true,
            'comment' => app::get('systemai')->_('商家总库存'),
            'label' => app::get('systemai')->_('商家总库存'),
            'order' => 18,
        ),
		'sale_num' => array(
            'type' => 'number',
			'default' => 0,
            'in_list' => false,
            'default_in_list' => false,
            'comment' => app::get('systemai')->_('销量'),
            'label' => app::get('systemai')->_('销量'),
			'order' => 19,
        ),
    ),
    'primary' => 'id',
    'index' => array (
        'ind_item_id' => ['columns' => ['item_id']],
        'ind_sku_id' => ['columns' => ['sku_id']],
        'ind_sale_num' => ['columns' => ['sale_num']],
    ),
    'comment' => app::get('systemai')->_('平台展销商品详情表'),
);